name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8
      with:
        toolchain: stable,esp

    - name: Run tests for mess_lib
      working-directory: mess_lib
      run: cargo test

    - name: Build project esp
      working-directory: esp
      run: cargo build
